language: python

python:
  - "3.6"
  - "3.7"

env:
  - TOX_ENV=py37-django-22
  - TOX_ENV=py36-django-22
  - TOX_ENV=py37-django-30
  - TOX_ENV=py36-django-30
  - TOX_ENV=py37-django-31
  - TOX_ENV=py36-django-31

matrix:
  fast_finish: true

install: pip install -r requirements_test.txt

script: tox -e $TOX_ENV

after_success:
  - codecov -e TOX_ENV
