language: python

matrix:
  fast_finish: true
  include:
    - env: TOXENV=lint
    # Python 3.6
    - python: 3.6
      env: TOXENV=py36-django22,py36-django30,py36-django31

    # Python 3.7
    - python: 3.7
      env: TOXENV=py37-django22,py37-django31,lint



install: pip install -r requirements_test.txt

script: tox

after_success:
  - codecov
